### ISSUE TITLE
protocol test dislikes windows

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#367]
I'm pretty sure this is a windows only phenomenon. But one of the tests fails for me locally:

```
Summary of all failing tests
 FAIL  src\utils\protocol\__tests__\protocolPath.test.js
  ● protocolPath › Electron › Generates an asset path for the file

    expect(received).toEqual(expected)

    Expected value to equal:
      "tmp/mock/user/path/protocols/foo.canvas/protocol.json"
    Received:
      "tmp\\mock\\user\\path\\protocols\\foo.canvas\\protocol.json"

      at Object.it (src/utils/protocol/__tests__/protocolPath.test.js:18:7)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by rebeccamadsen** [comment]
Is something like this acceptable?
```
expect(
        protocolPath('foo.canvas', 'protocol.json'),
      ).toMatch(/tmp(\/|\\)mock(\/|\\)user(\/|\\)path(\/|\\)protocols(\/|\\)foo\.canvas(\/|\\)protocol\.json/);
```
